apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: emojicode
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: .
    repoURL: https://github.com/telliott-io/emojicode-playground-deploy
    targetRevision: HEAD
  syncPolicy:
    automated: {}